version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 9487:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=CPDiscussion
      - MONGO_INITDB_ROOT_PASSWORD=94879487