// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Member struct {
	ID         string `json:"_id"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	IsAdmin    bool   `json:"isAdmin"`
	Username   string `json:"username"`
	Nickname   string `json:"nickname"`
	AvatarPath string `json:"avatarPath"`
}

type NewMember struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	IsAdmin    bool   `json:"isAdmin"`
	Username   string `json:"username"`
	Nickname   string `json:"nickname"`
	AvatarPath string `json:"avatarPath"`
}
